spring:
  application:
    name: subscription-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:reviews?useSSL=false&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: testuser
    password:
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVICE}
      group-id: group_id_newsletter
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ${KAFKA_SERVICE}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8082

topic:
  email: email

security:
  username: adidas
  password: adidas
